config_spec:
  hmac_secret:
    default: '{{ RandomString 64 }}'
  postgres_user:
    default: '{{ RandomString 32 }}'
  postgres_password:
    default: '{{ RandomString 64 }}'
  postgres_host:
    default: 'postgres'
  postgres_port:
    default: '5432'
  embedded_postgres:
    default: "true"
  namespace:
    description: "Kubernetes namespace to deploy SuperBigTool into. Will be created if it does not exist"
    default: superbigtool
  private_registry_api:
    description: "A private docker registry accessible by your cluster"
